import axios from "axios";
import { validateDataObject } from "@utils";
import { GetOauthData, OauthToken } from "@type";

/**
 * Exchanges an authorization code for an access token.
 * 
 * @example
 * import { getOauthToken } from "@kash.88/alerts";
 * 
 * // The "code" is received after the user authorizes your application
 * // via the link generated by "getAuthorizeLink".
 * 
 * try {
 *   const tokenData = await getOauthToken({
 *     client_id: "YOUR_CLIENT_ID",
 *     client_secret: "YOUR_CLIENT_SECRET",
 *     code: "AUTHORIZATION_CODE"
 *   });
 * 
 *   console.log(tokenData.access_token);
 * } catch (error) {
 *   console.error("Error getting Oauth token:", error.response.data);
 * }
 * 
 * @param {GetOauthData} data - The data for the token request.
 * @returns {Promise<OauthToken>} A promise that resolves to the token data from the API.
 * @see {@link https://www.donationalerts.com/apidoc#authorization__authorization_code__getting_access_token}
 */

export default async function getOauthToken(data: GetOauthData): Promise<OauthToken> {
    try {
        validateDataObject(data, ["client_id", "client_secret", "code"]);

        const response = await axios.post<OauthToken>("https://www.donationalerts.com/oauth/token", {
            grant_type: "authorization_code",
            client_id: data.client_id,
            client_secret: data.client_secret,
            code: data.code
        });

        return response.data;
    } catch (error: any) {
        throw new Error(error?.response?.data?.error_description || error?.message || error);
    }
} 